version: "3.8"
services:
  frontend:
    image: ghcr.io/Pad2806/convert_nextjs_to_nestjs_fe:latest
    container_name: frontend_prod
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}